### ISSUE TITLE
Broken mapping rows 2-6

### ISSUE THREAD

**Issue by Michaelknubben** [zsteinkamp/m4l-Modulation-Lerp#1]
Hi,

Great device, but I believe I've found an issue. Rows 2-6 in the multimapping screen seem to be broken, so everything that's in the area where the oscilloscope is. Above and below that (row 1, 7 and 8) all work.
![image](https://github.com/zsteinkamp/m4l-Modulation-Lerp/assets/27723800/e382890a-2a44-4ee8-8127-9249db5a9ab1)
This is in Live 11.3.21

Michael

**Comment by zsteinkamp** [comment]
Thank you @Michaelknubben! The mapping panel was hidden behind the graphical display, and so clicks weren't registering. I've pushed a fixed version here: https://github.com/zsteinkamp/m4l-Modulation-Lerp/raw/main/frozen/Modulation%20Lerp%20v2.amxd

I appreciate the bug report. :)
